version: "3.3"

services:

  watchman:
    build: .
    image: "watchman:latest"
    hostname: watchman
    environment:
      - TZ=Europe/Warsaw
    restart: "no"
    container_name: "watchman"
    networks:
      mynet:
        aliases:
          - watchman
    volumes:
      - "./root:/root"
    command:
      - "/start.sh"
networks:
  mynet:
    external:
     name: mynet

